# Generated by Django 5.1.4 on 2025-01-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(related_name='tasks', to='labels.label', verbose_name='Метки'),
        ),
    ]
